name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install rustlings
        run: |
          cargo install --force --path .
          cd learn_rust_rustlings-gu-pingsheng
          rustlings --help
      - uses: education/autograding@v1
